title: Zuhaib Hussain Butt
logo: /assets/img/zuhaibhussain.png
description: Data Scientics,assisting enterprises by supporting data-driven decision-making.
show_downloads: false
theme: jekyll-theme-minimal
